esphome:
  name: beer-button
  friendly_name: Beer Button

esp8266:
  board: nodemcu

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret beerbutton_api_encryption_key

ota:
  - platform: esphome
    password: !secret beerbutton_ota_pw

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_psk

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Beer-Button Fallback Hotspot"
    password: !secret beerbutton_fallback_ap_pw

captive_portal:

text_sensor:
  - platform: version
    name: "Beer Button ESPHome Version"

binary_sensor:
  - platform: gpio
    pin:
      number: D2
      mode: INPUT_PULLUP
      inverted: True
    name: "Beer Button"
