esphome:
  name: beer-button
  friendly_name: Beer Button

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret beerbutton_api_encryption_key

ota:
  - platform: esphome
    password: !secret beerbutton_ota_pw

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_psk

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Beer-Button Fallback Hotspot"
    password: !secret beerbutton_fallback_ap_pw

captive_portal:

text_sensor:
  - platform: version
    name: "Beer Button ESPHome Version"

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: GPIO48
    num_leds: 1
    name: "NeoPixel Light"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO11
      mode: INPUT_PULLUP
      inverted: True
    name: "Beer Button"
    
