esphome:
  name: raumfuhler-serverraum-3og
  friendly_name: Raumfühler Serverraum 3.OG

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

prometheus:

ota:
  - platform: esphome
    password: !secret datacenter_3og_ota_pw

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO17
    mode: CLK_OUT
  phy_addr: 0
  power_pin: GPIO12


i2c:
  sda: GPIO2
  scl: GPIO1

web_server:
  port: 9123

bme68x_bsec2_i2c:
  address: 0x77
  model: bme680

sensor:
  - platform: bme68x_bsec2
    temperature:
      name: "Serverraum 3.OG Temperatur"
      filters:
        - calibrate_linear:
            - 25.0 -> 23.0
            - 5.2 -> 4.1
    pressure:
      name: "Serverraum 3.OG Luftdruck"
    humidity:
      name: "Serverraum 3.OG Luftfeuchtigkeit"
    iaq:
      name: "Serverraum 3.OG IAQ"
    co2_equivalent:
      name: "Serverraum 3.OG CO2"
    breath_voc_equivalent:
      name: "Serverraum 3.OG VOC"
