esphome:
  name: sonoff_1645
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret sonoff_1645_wifi_static_ip
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
  domain: !secret wifi_domain

logger:

api:
  password: !secret sonoff_1645_api_password

ota:
  password: !secret sonoff_1645_api_password

binary_sensor:
- platform: gpio
  name: "Sonoff Basic Button"
  device_class: power
  pin:
    number: GPIO0
    mode: INPUT_PULLUP
    inverted: True
  on_press:
  - switch.toggle: relay

switch:
- platform: gpio
  name: "Sonoff Basic Relay"
  pin: GPIO12
  id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
